### ISSUE TITLE
Copyrighted Doom sprite

### ISSUE THREAD

**Issue by leilei-** [CireG/Zauberer#2]
The mage bloodscourge uses copyrighted Skulltag and Doom assets.

Please don't do copyrighted placeholders and submit them.  It completely misses the point of a Free media project.

EDIT: Here's a full list of suspicious lumps:

CHLYA0 - Strife, Samsara-Addons
CHLYB0 - Strife, Samsara-Addons
CHLYC0 - Strife, Samsara-Addons
CHLYD0 - Strife, Samsara-Addons
CHLYE0 - Strife, Samsara-Addons
CHLYF0 - Strife, Samsara-Addons
CHLYG0 - Strife, Samsara-Addons
MSTFA0 - Skulltag
MSTFB0 - Skulltag
MSTFC0 - Skulltag
MSTFD0 - Skulltag
MSTFE0 - Skulltag
MSTFF0 - Skulltag
MSTFG0 - Skulltag, Doom
MSTFH0 - Skulltag, Doom
MSTFI0 - Skulltag, Doom
MSTFJ0 - Skulltag

also i thought this was going to be a fantasy thing.... aliens, wtf?

**Comment by CireG** [comment]
Sorry, I thought those sprites were freely licensed. Anyway, they're removed now.
