### ISSUE TITLE
Placeholder IWAD needed

### ISSUE THREAD

**Issue by CireG** [CireG/Zauberer#4]
A basic placeholder IWAD should be made to be used as a base for adding assets submitted to the Project.

**Comment by Voros2** [comment]
You try out DeuTex.
But since many of the files here haven't been adjusted for a WAD, i dont think it'll be very nice.

So why dont you first do that, then use Slade3 to allign the gfx, and put them in one wad? It is time consuming, but youll get what you want. 

Unfortunately, im limited at the moment, so i cant have a go myself.

**Comment by CireG** [comment]
I can start working on it in Slade 3, though it will take some time, and with the limited Resources that's available, it'll be hard to make a complete IWAD I Think, if not filling out with empty lumps.
I understand that you're limited now, though there's no rush, if you find time later I'd appreciate any help.
Also placeholder assets would be really appreciated, no matter how bad, since it's better than nothing.

**Comment by Voros2** [comment]
It doesnt HAVE to be an IWAD. Work it as a PWAD first.

Thats how Freedoom first started out.

**Comment by CireG** [comment]
Yes, I'm aware that's how Freedoom started. If it's prefered to do a PWAD first, I guess it's OK. Most other projects I know of started the other way though (The People's Doom, Blasphemer, Animosity/Freestrife, FreeWolf3D...) and it seems to me to be the best way, but considering the resources incompletness of Zauberer, perhaps it's not...?

**Comment by Voros2** [comment]
Itll be easier. When the time comes, then you can work on it as an IWAD.

**Comment by CireG** [comment]
Right, I'll start with a PWAD. And as you said, when the time comes, it can be completed into an IWAD. Until then, I guess this issue can be kept open? It's labeled as an enhancement, after all.

**Comment by CireG** [comment]
Okay, I added a test PWAD I quickly put together. I Think this is similar to what you mean.

**Comment by Voros2** [comment]
What this project needs is assets. Badly. I'm in contact with a cool mapper. I do not know if the guy can map for Hexen, but I'll ask.

**Comment by Voros2** [comment]
Close this conversation.

Announcements should be made at Doomworld, where most of the community is. Who visits Github for announcements?

**Comment by leilei-** [comment]
Me because I don't visit Doomworld anymore, and I shouldn't have to return to a hostile, reactionary environment when my concerns are primarily in development of content.
