### ISSUE TITLE
Sound Files

### ISSUE THREAD

**Issue by ghost** [CireG/Zauberer#9]
Hi, Cire! I've recreated gauntled sfx from Heretic: https://github.com/saniv/free-game-sfx/blob/master/electricity/electricity64-zap3.flac

maybe you could find it useful.

Freedoom mods just banned me for nothing over some 4chan post

**Comment by CireG** [comment]
Hi Nikita!

Could certainly be useful I guess, will check it out later. Will add it to my repository at least.

Also, check out your e-mail if you haven't already

**Comment by CireG** [comment]
And now it's been added, thanks!
